### PR TITLE
add github workflow diagram

### PR DESCRIPTION
**Pull request by KellyWang1126**
#52 #49 (broken link)

### CODE REVIEW

**Comment by laijasmine** [comment]
@KellyWang1126 can you ask Angel if we can credit the original creator of this image

**Comment by KellyWang1126** [comment]
@laijasmine I just got the link but where can we credit the original creator? Link: https://www.reddit.com/r/git/comments/99ul9f/git_workflow_diagram_showcasing_the_role_of/

**Comment by KellyWang1126** [comment]
And I found a new version of the diagram in the link Angel provided and I think I'll update the picture now.

**Comment by laijasmine** [comment]
yeah since it is on reddit people are anonymous but you can at least link back to the post and credit their username `stamminator`

**Pull request merged**
