### PR TITLE
SFTP files

### PR DESCRIPTION
**Pull request by KellyWang1126**
#214 #197 #208 #168 #205 #207 #206

### CODE REVIEW

**Comment by laijasmine** [comment]
@KellyWang1126 the checks have been failing due to a curl error. If you see any code chunks with something along the lines of:
```
cn_staging <- CNode('STAGING')
adc_test <- getMNode(cn_staging,'urn:node:mnTestARCTIC')
```

Can you make sure that `eval = F (for FALSE)` at the top of the code chunk?

I've been trying to figure out where the problem is in this PR:
https://github.com/NCEAS/datateam-training/pull/216

**Comment by KellyWang1126** [comment]
@laijasmine Will do tomorrow when I get in.

**Comment by KellyWang1126** [comment]
I only found one cn_staging code chunk has `eval = F` missing and add it back. Does this help with fixing the curl error?

**Comment by laijasmine** [comment]
It's still failed(indicated by the "All checks have failed below) but thank you for trying! I'll probably have to work on this problem a bit more

**Comment by KellyWang1126** [comment]
So is that okay for me to continue working on other data training issues for now with all the checks failed?

**Comment by laijasmine** [comment]
Yes it is fine. The problem shouldn't be related to the things you have been doing.

**Pull request closed without merging**
